# 에러/예외 처리 (Error/Exception Handling)

디버깅…어느 부분을 중점적으로 봐야 하는지?

: 제어가 되는 시점, 조건/반복, 함수

-   branches: 모든 조건이 원하는 대로 동작하는지
-   for loops: 반복문에 진입하는지, 원하는 횟수만큼 실행되는지
-   while loops: 반복문에 진입하는지, 종료조건이 제대로 동작하는지
-   function: 함수 호출시, 함수 파라미터, 함수 결과

-   print 함수 활용: 특정 함수
-   개발 환경 등에서 제공하는 기능 활용
-   Python tutor 활용
-   뇌컴파일, 눈디버깅

-   에러 메세지가 발생하는 경우: 해당 위치 찾아서 메세지 보고 해결
-   로직 에러가 발생하는 경우: 명시적 에러 메세지 없이 예상과 다른 결과가 나온 경우
    -   정상적으로 동작한 코드 이후 작성된 코드 되돌아보기
    -   전체 코드 살피기
    -   누군가에게 설명해보기…

## 에러와 예외

### 문법 에러(Syntax Error)

-   syntax error 발생하면 파이썬 프로그램은 실행되지 않음
-   파일이름, 줄번호, ^ 문자를 통해 파이썬이 코드를 읽어 나갈때 문제가 발생한 위치 표현
-   줄에서 에러가 감지된 가장 앞의 위치를 가리키는 캐럿 기호 ^ 를 표시

```python
if else

#File "<ipython-input 1 f8a097d0a685>", line 1
#if else ^
#SyntaxError: invalid syntax
```

EOL (End of Line)

```python
print('hello
#File "<ipython-input-6-2a5f5c6b1414>", line 1
# print('hello
#             ^
# SyntaxError: EOL while scanning string literal
```

EOF (End of File)

```python
print(
# File "<ipython-input 4 424fbb3a34c5>", line 1
# print(
#     ^
#SyntaxError : unexpected EOF while parsing
```

Invalid syntax

```python
while
# File "<ipython-input 7 ae84bbebe3ce>", line 1
# while
#          ^
#SyntaxError : invalid syntax
```

assign to literal

```python
5 = 3
# File "<ipython-input-28-9a762f2c796b>", line 1
# 5 = 3
# ^
# SyntaxError: cannot assign to literal
```

### 예외(Exception)

-   실행 도중 예상치 못한 상황을 맞이하면, 프로그램 실행을 멈춤
    -   문장이나 표현식이 문법적으로 올바르더라도 발생하는 에러
-   실행 중에 감지되는 에러들을 예외(Exception)라고 부름
-   예외는 여러 타입으로 나타나고, 타입이 메세지의 일부로 출력됨
    -   NameError, TypeError 등 발생한 예외 타입의 종류(이름)
-   모든 내장 예외는 Exception Class를 상속받아 이뤄짐
-   사용자 정의 예외를 만들어 관리할 수 있음

ZeroDivisionError: 0으로 나누고자 할 때 발생

```python
10/0
#------------
#ZeroDivisionError Traceback (most recent call last)
#--------> 1 10/0
#ZeroDivisionError : division by zero
```

NameError: namespace 상에 이름이 없는 경우

```python
print(name_error)
#-------------
#NameError Traceback (most recent call last)
#--------> 1 name_error
#NameError : name name_error ' is not defined
```

TypeError: 타입 불일치

```python
1 + '1'
#----------------
#TypeError Traceback (most recent call last)
#--------> 1 1 + '1'
#TypeError : unsupported operand type(s) for +: 'int' and '
```

```python
round('3.5')
#--------------
#TypeError Traceback (most recent call last)
#--------> 1 round('3.5')
#TypeError : type str doesn't define __round__ method
```

TypeError: argument 부족

```python
divmod()
#----------
#TypeError Traceback (most recent call last)
#--------> 1 divmod
#TypeError : divmod expected 2 arguments, got 0
```

```python
import random
random.sample()
# ---------
# TypeErrorTraceback (most recent call last)
#       1 import random
# ----> 2 random.sample()
# TypeError: sample() missing 2 required positional arguments: 'population' and 'k'
```

TypeError: argument 개수 초과

```python
divmod(1 , 2 , 3)
#----------------
#TypeError Traceback (most recent call last)
#--------> 1 divmod (1, 2,
#TypeError : divmod expected 2 arguments, got 3
```

```python
import random
random.sample(range (3), 1 , 2)
#-------------
#TypeError Traceback (most recent call last)
#          1 import random
#--------> 2 random.sample (range(3), 1,
# TypeError : sample() takes 3 positional arguments but 4 were given
```

ValueError: 타입은 올바르나 값이 적절하지 않거나 없는 경우

```python
int('3.5')
# ------
# ValueErrorTraceback (most recent call last)
# ----> 1 int('3.5')
# ValueError: invalid literal for int() with base 10: '3.5'
```

```python
range(3).index(6)
#----------
#ValueError Traceback (most recent call last)
#--------> 1 range(3).index(
#ValueError : 6 is not in range
```

IndexError

```python
empty_list = []
empty_list[2]
#------------
#IndexError Traceback (most recent call last)
#          1 empty_list =
#--------> 2 empty_list [
#IndexError : list index out of range
```

KeyError

```python
song = {'Nothing But Thieves': 'Honey Whiskeky'}
song['The Vamps']

#----------
#KeyError Traceback (most recent call last)
#          1 song = {'Nothing But Thieves': 'Honey Whiskeky'}
#--------> 2 song['The Vamps']
#KeyError : 'The Vamps'
```

ModuleNotFoundError: 존재하지 않는 모듈을 import 하는 경우

```python
import nonamed
#------------
#ModuleNotFoundError Traceback (most recent call last)
#--------> 1 import nonamed
#ModuleNotFoundError : No module named nonamed
```

ImportError: Module은 있으나 존재하지 않는 클래스/함수를 가져오는 경우

```python
from random import samp
#--------------
#ImportError Traceback (most recent call last)
#--------> 1 from random import samp
#ImportError : cannot import name 'samp' from 'random'
```

IndentationError: Indentation이 적절하지 않는 경우

```python
for i in range(3):
print(i)
# File "<ipython-input 56 78291925d94f>", line 2
# print(i)
# ^
#IndentationError : expected an indented block
```

KeyboardInterrupt: 임의로 프로그램을 종료했을 때

```python
while True:
	continue
#---------
#KeyboardInterrupt Traceback (most recent call last)
# <ipython-input 55 6a65cf439648> in <module>
#          1 while True:
#--------> 2 continue
#KeyboardInterrupt :
```

## 예외처리

-   try문(statement) / except절(clause)을 이용하여 예외 처리를 할 수 있음
-   try문
    -   오류가 발생할 가능성이 있는 코드를 실행
    -   예외가 발생되지 않으면, except 없이 실행 종료
-   except문
    -   예외가 발생하면, except절이 실행
    -   예외 상황을 처리하는 코드를 받아서 적절한 조치를 취함

```python
try:
	try 명령문
except 예외그룹-1 as 변수-1:
	예외처리 명령문 1
except 예외그룹-2 as 변수-2:
	예외처리 명령문 2
finally: (선택사항)
	finally 명령문

#주의: try문은 반드시 한 개 이상의 except문이 필요
```

```python
numbers = input('숫자를 입력해주세요: ')
print(numbers)

try:
	if int(numbers) == 5:
			print('5 입니다')
	else:
			print('5가 아닙니다')
except:
	print('숫자를 입력하지 않았습니다.')
```

```python
#100을 사용자가 입력한 숫자로 나눠서 결과를 출력
number = input()

try:
	print(100/int(number))
except ZeroDivisionError:
	print(err) #파이썬 에러 메세지도 같이 출력
	print('0으로 나눌 수는 없습니다.')
except ValueError:
	print('오류')
```

-   try: 코드를 실행
-   except: try문에서 예외가 발생 시 실행
-   else: try문에서 예외가 발생하지 않으면 실행
-   finally: 예외 발생 여부와 관계없이 항상 실행

### 예외처리 예시

파일을 열고 읽는 코드를 작성하는 경우

```python
#파일이 없는 경우
try:
	f = open ('nooofile.txt')
except FileNotFoundError:
	print('해당 파일이 없습니다')
else:
	print('파일을 읽기 시작합니다')
	print(f.read())
	print('파일을 모두 읽었습니다')
	f.close()
finally:
	print('파일 읽기를 종료합니다')
```

```python
# 파일이있는경우
try:
	f = open('file.txt')
except FileNotFoundError:
	print('해당파일이없습니다.')
else:
	print('파일을읽기시작합니다.')
	print(f.read())
	print('파일을모두읽었습니다.')
	f.close()
finally:
	print('파일읽기를종료합니다.')
```

## 예외 발생 시키기

raise를 통해 예외를 강제로 발생

`raise <표현식> (메세지)`

```python
raise
#--------
#RuntimeError Traceback (most recent call last)
#--------> 1 raise
#RuntimeError : No active exception to reraise
```
